language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master
    - /^\d+\.\d+$/
    - /^\d+\.x$/

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: hhvm


install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - make $TARGET

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
